language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

before_script:
  - mkdir bootstrap/cache
  - cp .env.travis .env
  - mysql -e 'create database dbtest;'
  - composer install --no-interaction
  - php artisan migrate:install
  - php artisan db:seed
  - php artisan passport:install

script:
  - vendor/bin/phpunit
