language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

before_install:
  -  chmod +x ./tests/scripts/*
  - ./tests/scripts/travis_mysql_5.7.sh
  - ./tests/scripts/travis_mysql_reset_root_password.sh

before_script:
  - mkdir bootstrap/cache
  - cp .env.travis .env
  - mysql -e 'create database dbtest;'
  - composer install --no-interaction
  - chmod -R 777 storage/
  - php artisan migrate:install --no-interaction -vvv
  - php artisan migrate --no-interaction -vvv
  - php artisan db:seed --no-interaction -vvv
  - php artisan passport:install

script:
  - vendor/bin/phpunit
