language: php

sudo: true

php:
  - '5.6'
  - '7.0'
  - '7.1'

before_install:
  - bash ./tests/scripts/travis_install_mysql_5.7.sh
  - mysql --version

before_script:
  - mkdir bootstrap/cache
  - cp .env.travis .env
  - mysql -e 'create database dbtest;'
  - composer install --no-interaction
  - chmod -R 777 storage/
  - php artisan migrate:install --no-interaction -vvv
  - php artisan migrate --no-interaction -vvv
  - php artisan db:seed --no-interaction -vvv
  - php artisan passport:install

script:
  - vendor/bin/phpunit
